name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: . ./install.ps1 -Force "${{ matrix.force }}"
      - name: Show "$HOME"
        shell: bash
        run: ls -la "$HOME"
      - name: Test installed files
        shell: bash
        run: |
          set -exo pipefail
          workspace="/$(printf '%s\n' "${{ github.workspace }}" | tr '\' '/' | tr -d ':' | tr "[:upper:]" "[:lower:]")"
          ls -la "$HOME" | grep .gitconfig | grep "${workspace}/.gitconfig"
          ls -la "$HOME" | grep .gitignore_global | grep "${workspace}/.gitignore_global"
          ls -la "$HOME/.docker" | grep daemon.json | grep "${workspace}/home/.docker/daemon.json"
          ls -la "$HOME/.ssh" | grep config | grep "${workspace}/home/.ssh/config"
