name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dotfiles
        run: . ./install.ps1 -Force "${{ matrix.force }}"
      - name: Show "$HOME"
        shell: bash
        run: ls -la "$HOME"
      - name: Test installed files
        shell: bash
        run: |
          set -exo pipefail
          workspace="/$(printf '%s\n' "${{ github.workspace }}" | tr '\' '/' | tr -d ':' | tr "[:upper:]" "[:lower:]")"
          ls -la "$HOME" | grep .wslconfig | grep "${workspace}/.wslconfig"
          ls -la "$HOME" | grep .textlintrc.json | grep "${workspace}/.textlintrc.json"
          ls -la "$HOME/.config/git" | grep config | grep "${workspace}/home/.config/git/config"
          ls -la "$HOME/.config/git" | grep ignore | grep "${workspace}/home/.config/git/ignore"
          ls -la "$HOME/.docker" | grep daemon.json | grep "${workspace}/home/.docker/daemon.json"
          ls -la "$HOME/.ssh" | grep config | grep "${workspace}/home/.ssh/config"
