name: Release
on:
  push:
    tags: ['*.*.*']        # 1.2.3

jobs:
  publish:
    runs-on: windows-latest # Native AOT should be built on Windows
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Verify tag is pure semver x.y.z
        shell: bash
        env:
          TAG: ${{ github.ref_name }}
        run: |
          if [[ ! "${TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Tag '${TAG}' is not a pure semantic version (x.y.z)."
            exit 1
          fi
          echo "Tag $TAG validated."
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x
      - name: dotnet publish (Native AOT)
        shell: bash
        run: dotnet publish --artifacts-path ./publish
      - name: Create zip
        shell: pwsh
        run: |
          $pub = "publish/publish/DotfilesLinker/release_win-x64"
          Compress-Archive -Path "$pub/*" -DestinationPath DotfilesLinker-win-x64.zip
      - name: Create GitHub Release via gh
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" --title "v$TAG" --generate-notes --fail-on-no-commits DotfilesLinker-win-x64.zip
